name: Copy .github/workflows to vimrc-setup

# generates the english translation files
# git clones the openedx-translations
# finds and copies the relevant translation files from the current repo to openedx-translations
# git adds, commits, & pushes them to openedx-translations

on:
  workflow_dispatch: {}

jobs:
  myjob:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout source repo
        uses: "actions/checkout@v3"
        with:
          path: source
      
      - name: checkout another repo
        uses: "actions/checkout@v3"
        with:
          repository: Carlos-Muniz/vimrc-setup
          path: target
      
      - name: Copy .github/workflows/*.yml to vimrc-setup
        run: find ./source -iname '*.yml' -exec cp -v --parents {} ./target/ \;
      
      - name: commit files to vimrc-setup repo
        run: |
            git config --global user.email "cmuniz.dev@gmail.com"
            git config --global user.name "Carlos Muniz"
            cd ./target
            git add .
            git diff-index --quiet HEAD || git commit -m "Automatic publish via workflow"
            git push vimrc-setup main
